#!/bin/bash
SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )"

sourceDirectory=${1}
release=${2}
uploadSpec=${UPLOAD_SPEC:-${3:-"${SCRIPT_HOME}/upload-spec.json"}}

export JFROG_CLI_LOG_LEVEL=DEBUG

fileList=$(find "${sourceDirectory}" -type f -name '*.deb' -mindepth 1 -maxdepth 1 -printf "%f\n" 2>/dev/null)
for packageName in ${fileList}; do
  packageShortName=$(echo "${packageName}" | sed -rn 's~^(python3-)?([^.]*)_.*.deb~\2~p')
  packageArchitecture=$(echo "${packageName}" | sed -rn 's~^.*_(.*).deb~\1~p')
  packageStartingLetter=$(echo "${packageShortName}" | sed -rn 's~^(.).*~\1~p')

  echo "====================================================================================================================="
  echo "packageName: ${packageName}"
  echo "packageShortName: ${packageShortName}"
  echo "packageArchitecture: ${packageArchitecture}"
  echo "packageStartingLetter: ${packageStartingLetter}"
  echo "release: ${release}"
  echo "uploadSpec: ${uploadSpec}"
  echo "---------------------------------------------------------------------------------------------------------------------"
  jfrog rt u \
    --deb xenial/${release}/${packageArchitecture} \
    --spec ${uploadSpec}\
    --spec-vars "SOURCE_DIR=${sourceDirectory};PACKAGE_NAME=${packageName};RELEASE=${release};PACKAGE_STARTING_LETTER=${packageStartingLetter};PACKAGE_SHORT_NAME=${packageShortName}" \
    --detailed-summary
  echo "====================================================================================================================="
  echo
done