name: "Publish Debian Packages"
description: ""

inputs:
  sourceDirectory:
    description: "The directory containing the packages to be published."
    required: true
  distribution:
    description: "The distribution supported by the package. i.e xenial, focal, etc."
    required: true
  component:
    description: "The component type.  i.e. stable, rc, dev"
    required: true

runs:
  using: "composite"
  steps:
    - name: Publish
      shell: bash
      run: |
        ${{ github.action_path }}/publishPackages "${{ inputs.sourceDirectory }}" "${{ inputs.distribution }}" "${{ inputs.component }}"
